### ISSUE TITLE
How to get this run?

### ISSUE THREAD

**Issue by GaryCooper23** [linuxkidd/venus-teslabms#1]
Hello Michael, would you please share how to get this run? My Setup is a Cerbo GX and Arduino Due. I was able to get data from the original [TeslaBMS](https://github.com/collin80/TeslaBMS) on Serial Monitor. I want to use an newer version to get a better battery balancing. Also i want to get the Battery data in Venus OS, SoC would be great.

Your TeslaBMSV2 is just for SimpBMS Boards? While on your TeslaBMS package i dont get any data on Serial Monitor.

**Comment by linuxkidd** [comment]
Hi Gary,
  Apologies for the sorry state of documentation on this project.  I was using it in more of a dev mode and never got to the point of an easy to install tool.  But, here are the highlights:
  
  1. The Arduino Due running [TeslaBMS](https://github.com/linuxkidd/TeslaBMS) is plugged into a USB port on the CerboGX
  2. I SSH'd into the CerboGX, and manually stopped / blocked the in-built serial handling of the connected Due device using [svc](https://cr.yp.to/daemontools/svc.html) command.
  3. I then start a `screen` instance and manually execute `teslabms.py -p /dev/ttyXXX`, using the proper path to the Due's USB tty.
  
  Note that I was never able to get the i2c shunt working directly on the Due that is operating the BMS, even though it seems it should have been very possible.  I don't know if the serial timing hacks that is needed for the BMS to operate at  617647 baud that was causing i2c interfaces to fail.
  
For that reason, I moved the i2c shunt onto a separate Arduino Nano, then connected the serial pins from the Nano to one of the Serial pin sets on the Due.  This allowed me to get both the shunt and bms data in one connection to the CerboGX.  I just pushed the code for this into my [ina219_shunt](https://github.com/linuxkidd/ina219_shunt) repo.

fwiw, I never found that the Tesla modules needed balancing, so I never pursued that functionality beyond mostly disabling it by setting such a high balance voltage.

I've since stopped full time RV travel, and have my coach up for sale with the Victron gear installed, so I won't be continuing the project personally.  If you would like to finalize the CerboGX side to be easily installed, I'd gladly accept a PR, or you are of course, more than welcome to fork the project as well.

I used a lot of info from [dbus-serialbattery](https://github.com/Louisvdw/dbus-serialbattery) to get as far as I did.. It would be good to use their install process as a base for getting this project to be easier to install and run.

I'm happy to answer any other questions you may come up with along the way.

**Comment by GaryCooper23** [comment]
Thanks for the fast response, I will test the steps tomorrow 🙂

**Comment by GaryCooper23** [comment]
I've tried but i'm not able to get this run:

 ps | grep ttyACM0
 1367 root      1612 S    supervise dbus-serialbattery.ttyACM0
 1370 root      1756 S    multilog t s25000 n4 /var/log/dbus-serialbattery.ttyACM0
22974 root      1612 S    supervise gps-dbus.ttyACM0
22987 root      1624 S    multilog t s25000 n4 /var/log/gps-dbus.ttyACM0
23074 root      1612 S    supervise vedirect-interface.ttyACM0
23085 root      1624 S    multilog t s25000 n4 /var/log/vedirect.ttyACM0
28327 root     20408 S    python /opt/victronenergy/dbus-serialbattery/dbus-serialbattery.py /dev/ttyACM0
28353 root      2692 R    grep ttyACM0

I think this is the right device, used by dbus-serialbattery, by running `/opt/victronenergy/teslabms/teslabms.py -p /dev/ttyACM0` i get the error: modulenotfounderror: no module named 'vedbus'

Any idea?

**Comment by linuxkidd** [comment]
Hi Gary,
  You can confirm the right `tty` by using `dmesg`.  It'll print a few lines whenever the Due is plugged in, including the `tty` device assigned.  However, `ttyACM0` seems very likely to be correct.

Re: the `no module named 'vedbus'` message... 

I just pushed an update to point to the correct path for the `vedbus` python modules ( based on what's in `dbus-serialbattery` code now.. )

Let me know if that takes care of it! :)

NOTE: With the other services using `ttyACM0`, it's likely you'll get a denial on trying to open the port.  The following, *might* terminate those other services and allow the `teslabms.py` code to use the port:
```
svc -d dbug-serialbattery.ttyACM0
svc -d vedirect-interface.ttyACM0
rm -rf /service/dbus-serialbattery.ttyACM0
rm -rf /service/vedirect-interface.ttyACM0
ln -s /service/dbus-serialbattery.ttyACM0 /dev/null
ln -s /service/vedirect-interface.ttyACM0 /dev/null
```
These commands should be copy/pasted as a block.  Delays between steps might allow the system time to re-create the services before you link them to `/dev/null`.

Unfortunately, I don't have a CerboGX to test on at this point.. so, ymmv.

**Comment by GaryCooper23** [comment]
First success... ive got the Tesla BMS Menu in Venus OS. But there are no Information from the Modules except the variables from teslabms.py. i have changed the Modules to 2.

How do you connected the can signal? had it working on pins 18 and 19 and 5V and GND on the original TeslaBMS.

**Comment by linuxkidd** [comment]
Hi Gary,
  In [TeslaBMS config.h](https://github.com/linuxkidd/TeslaBMS/blob/master/config.h#L16), the BMS serial is set to `Serial1`.  This defaults to pin 18/19 for tx/rx respectively.  
  
Note that there's no CAN bus code in my version of `TeslaBMS` -- but the BMB comms are serial.. so that shouldn't be a problem.

**Comment by GaryCooper23** [comment]
I cant refine the issue...

Do i need your dbus or the current [dbus-serialbattery](https://github.com/Louisvdw/dbus-serialbattery)

Also can i check the serial communication on serial monitor in Arduino IDE in the Serial Monitor? Running the original TeslaBMS i receive a menu, on your fork there comes and goes nothing on the Serial Monitor, Maybe thats the issue?

**Comment by linuxkidd** [comment]
Hi Gary,
  Sorry I wasn't more clear.  There's no need for the `dbus-serialbattery` code or anything else to be installed for the code from my repo to work.
  
The Arduino [TesaBMS](https://github.com/linuxkidd/TeslaBMS/) I modified is needed for this `venus-teslabms` to work because I changed the output format and had it go directly into dumping the values with no input needed.

If you have data using the other TeslaBMS code, you should be able to flash my code and get data as well, just no menu to worry with ( although, most of the menu commands do still work ).

Note that no output will be generated by my fork of TeslaBMS unless it gets data from the Tesla BMB's.

**Comment by GaryCooper23** [comment]
That's even better, alright i will check again later! Thank you very much for helping me!

**Comment by GaryCooper23** [comment]
I changed the Serial port in Arduino IDE to SerialUSB and connected the Arduino directly via USB to the CerboGX, now i get some values:

![Screenshot 2023-08-10 090445](https://github.com/linuxkidd/venus-teslabms/assets/115779675/848aa710-b3ba-42a3-81a4-2e112097c8af)
![Screenshot 2023-08-10 092322](https://github.com/linuxkidd/venus-teslabms/assets/115779675/ea863e3e-9c21-4798-9860-ed6b35b3d7e8)

One more success... in my case I'm running 2 modules in series so it need to sum up the Voltages, would you help me to edit the code? My only help ist ChatGPT-4 and its dump even Code Interpreter...

**Comment by GaryCooper23** [comment]
Im closing this issue, in fact you helped me to get this working, so i will continue to edit it for my setup. Thanks for helping!

**Comment by linuxkidd** [comment]
Hi @GaryCooper23 ... I'm concerned that your data doesn't include the high/low cell voltages and temperatures.   Feel free to open this, or another issue if you run into things you need further assistance with.

o/
